v2

diff --git a/.local/bin/pomo b/.local/bin/pomo
--- a/.local/bin/pomo
+++ b/.local/bin/pomo
@@ -1,18 +1,53 @@
-#!/bin/zsh
+#!/bin/bash
 
-while true; do
-	for i in {1..4}; do
-		peaclock --config "./.peaclock/config/pomowork"
-		while true; do
-			vared -p 'Continue? (y/n): ' -c confirm
-			if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
-				if [[ $i = 4 ]]; then
+if [ -n "$TMUX" ]; then
+	trap "tmux set automatic-rename on" exit SIGTERM SIGINT
+	tmux rename-window 'pomo'
+fi
+
+confirmation() {
+	while true; do
+		for i in {1..4}; do
+			peaclock --config "./.peaclock/config/pomowork"
+			while true; do
+				read -e -p 'Continue? (y/n): ' confirm
+				if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
+					if [[ $i = 4 ]]; then
+						break
+					fi
+					unset confirm
+					peaclock --config "./.peaclock/config/pomoshortbreak"
+					while true; do
+						read -e -p 'Continue? (y/n): ' confirm
+						if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
+							unset confirm
+							break
+						elif [[ $confirm == [nN] || $confirm == [nN][oO] ]];then
+							tput reset
+							exit 0
+						else
+							unset confirm
+							echo "Invalid input."
+							continue
+						fi
+					done
 					break
+				elif [[ $confirm == [nN] || $confirm == [nN][oO] ]];then
+					tput reset
+					exit 0
+				else
+					unset confirm
+					echo "Invalid input"
+					continue
 				fi
+			done
+		done
+		while true; do
+			if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
 				unset confirm
-				peaclock --config "./.peaclock/config/pomoshortbreak"
+				peaclock --config "./.peaclock/config/pomolongbreak"
 				while true; do
-					vared -p 'Continue? (y/n): ' -c confirm
+					read -e -p 'Continue? (y/n): ' confirm
 					if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
 						unset confirm
 						break
@@ -32,37 +67,75 @@ while true; do
 			else
 				unset confirm
 				echo "Invalid input"
+				read -e -p 'Continue? (y/n): ' confirm
 				continue
 			fi
 		done
 	done
+}
+
+no-confirmation() {
 	while true; do
-		if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
-			unset confirm
-			peaclock --config "./.peaclock/config/pomolongbreak"
+		for i in {1..4}; do
+			start=$SECONDS
+			peaclock --config "./.peaclock/config/pomowork"
 			while true; do
-				vared -p 'Continue? (y/n): ' -c confirm
-				if [[ $confirm == [yY] || $confirm == [yY][Ee][sS] ]]; then
-					unset confirm
+				duration=$(( SECONDS - start))
+				if [[ $duration -ge 1499 ]]; then
+					if [[ $i = 4 ]]; then
+						break
+					fi
+					unset start
+					unset duration
+					start=$SECONDS
+					peaclock --config "./.peaclock/config/pomoshortbreak"
+					while true; do
+						duration=$(( SECONDS - start ))
+						if [[ $duration -ge 299 ]]; then
+							unset start
+							unset duration
+							break
+						else
+							tput reset
+							exit 0
+						fi
+					done
 					break
-				elif [[ $confirm == [nN] || $confirm == [nN][oO] ]];then
+				else
 					tput reset
 					exit 0
+				fi
+			done
+		done
+		while true; do
+			unset start	
+			unset duration
+			start=$SECONDS
+			peaclock --config "./.peaclock/config/pomolongbreak"
+			while true; do
+				duration=$(( SECONDS - start ))
+				if [[ $duration -ge 899 ]]; then
+					unset start
+					unset duration
+					break
 				else
-					unset confirm
-					echo "Invalid input."
-					continue
+					tput reset
+					exit 0
 				fi
 			done
 			break
-		elif [[ $confirm == [nN] || $confirm == [nN][oO] ]];then
-			tput reset
-			exit 0
-		else
-			unset confirm
-			echo "Invalid input"
-			vared -p 'Continue? (y/n): ' -c confirm
-			continue
-		fi
+		done
 	done
-done
+}
+
+case "$1" in
+	-c|--confirm)
+		confirmation
+		;;
+	-n|--no-confirm)
+		no-confirmation
+		;;
+	*)
+		no-confirmation
+		;;
+esac
